### ISSUE TITLE
跪求之前矿池文件！！被我删掉了，hookpool官网也没有了！现在想恢复solo恢复不了！！求发一份！

### ISSUE THREAD

**Issue by juyong5168** [allenlinkme/hookpool_client_chia#15]
跪求之前矿池文件！！被我删掉了，hookpool官网也没有了！现在想恢复solo恢复不了！！求发一份！好人一生平安！ 我的微信：Calm-waves

**Comment by allenlinkme** [comment]
https://github.com/allenlinkme/hookpool_client_chia/releases/tag/1.0

**Comment by allenlinkme** [comment]
正在彻夜努力，白天会出新版本，敬请耐心等待。

**Comment by rr-w** [comment]
矿池多久能好？

**Comment by Nobody-Lee** [comment]
> 正在彻夜努力，白天会出新版本，敬请耐心等待。

请问什么时候完成新版本

**Comment by allenlinkme** [comment]
> > 正在彻夜努力，白天会出新版本，敬请耐心等待。
> 
> 请问什么时候完成新版本

https://github.com/allenlinkme/hookpool_client_chia/releases  可以下载新版本
想要恢复旧版本和官方solo冲突：
1直接运行挖矿软件start_pool_mining.bat 即可检测修复并启动新版本挖矿服务
2 直接运行clear_pool_service.bat可以完全清除挖矿软件的服务和恢复官方solo
