### ISSUE TITLE
这矿池估计比hp还黑

### ISSUE THREAD

**Issue by rr-w** [allenlinkme/hookpool_client_chia#23]

**Comment by 463877775** [comment]
就是一个垃圾，前面测试的时候大推，然后就把所以文件软件都删除了，是不是有鬼啊，搞的官方软件都被劫持了，不能挖，就是垃圾货

**Comment by allenlinkme** [comment]
> 就是一个垃圾，前面测试的时候大推，然后就把所以文件软件都删除了，是不是有鬼啊，搞的官方软件都被劫持了，不能挖，就是垃圾货

我们从未大力推广，一直都是公测使用，官方solo和旧版本冲突，我大概解释下，旧版本我们共用了官方的配置，结果测试下来会有冲突，我们第一时间撤包就是为了保护后续想要下载使用的用户
新版本我们也上线了修复旧版本与官方solo冲突的功能
