### ISSUE TITLE
怎么举报这个垃圾啊，在哪里举报啊，前面的文件软件全部删除了，是不是有鬼，现在官方的都不能挖，被劫持了

### ISSUE THREAD

**Issue by 463877775** [allenlinkme/hookpool_client_chia#25]
怎么举报这个垃圾啊，在哪里举报啊，前面的文件软件全部删除了，是不是有鬼，现在官方的都不能挖，被劫持了

**Comment by allenlinkme** [comment]
请使用我们新版本恢复官方solo，对于旧版本造成的冲突，我们非常抱歉，使用clear_pool_service.bat可以完全修复官方solo
