### ISSUE TITLE
你好，我之前用富池跑了一下，现在无法solo，恢复solo的脚本再release只吓到了一个readme，求助，急！

### ISSUE THREAD

**Issue by caokangle** [allenlinkme/hookpool_client_chia#31]

**Comment by Nobody-Lee** [comment]
set port=8560
for /f "tokens=1-5" %%i in ('netstat -ano^|findstr "127.0.0.1:%port%"') do (
    echo kill the process %%m who use the port %port%
    taskkill  -f -pid %%m
)
set port=8447
for /f "tokens=1-5" %%i in ('netstat -ano^|findstr "127.0.0.1:%port%"') do (
    echo kill the process %%m who use the port %port%
    taskkill  -f -pid %%m
)
set current_path="%cd%"
cd %current_path%\daemon
chia pool_mining

**Comment by Nobody-Lee** [comment]
> _No description provided._

把以上代码复制到一个空白txt并更改后缀名为bat，放入矿池挖矿软件

**Comment by allenlinkme** [comment]
你好，我们发布了2.6的稳定版本，里边有直接运行可以修复旧版本与solo的冲突，或者直接运行clear_pool_service.bat清理旧版本与官方solo冲突问题
