### ISSUE TITLE
已组建（非官方）Q群79727800

### ISSUE THREAD

**Issue by zouxiao0916** [allenlinkme/hookpool_client_chia#48]
已组建Q群79727800  欢迎大家一起学习 探讨

**Comment by Nobody-Lee** [comment]
> 已组建Q群79727800 欢迎大家一起学习 探讨

你好，我已经组建了，群号285797980

**Comment by allenlinkme** [comment]
为何要建群，有问题github提不好吗？chia官方也没建什么群
