### ISSUE TITLE
贡献点异常

### ISSUE THREAD

**Issue by Jason-xy** [allenlinkme/hookpool_client_chia#60]
贡献点异常，算力显示正常，连续12小时贡献点没有随时间增加。
![image](https://user-images.githubusercontent.com/53471811/120874896-52a53300-c5db-11eb-9aff-3fa280a6eccd.png)

**Comment by allenlinkme** [comment]
你的贡献点会增加的话 才不正常，你对比下你的算力和下面的贡献值

**Comment by Jason-xy** [comment]
> 你的贡献点会增加的话 才不正常，你对比下你的算力和下面的贡献值

噢噢懂了 刚开始的时候贡献点会慢慢增长到算力值就稳定了

**Comment by allenlinkme** [comment]
我们计算规则就是，不在线的矿机，每过一轮计算，贡献值就会减半
